name: test suite
on: 
    push:
      tags:
      - '*'

jobs:
    build:
        name: build release binaries
        strategy:
            fail-fast: false
            matrix:
                os: ["ubuntu-latest"]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: install rust
              uses: dtolnay/rust-toolchain@stable
            - name: install cross
              run: |
                cargo install cross --git https://github.com/cross-rs/cross
            - name: build unix
              if: contains(matrix.os, 'ubuntu')
              run: |
                cross build --profile optimized --locked --target aarch64-unknown-linux-gnu
                tar -czf "qwert-${{github.ref_name}}-aarch64-linux-gnu.tar.gz" --transform 's|.*/||' "target/aarch64-unknown-linux-gnu/optimized/qwert"
                ls -alh
            - name: build macos
              if: contains(matrix.os, 'macos')
              run: |
                cargo build --profile optimized --locked
                ls -alh target
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: release-binaries
                path: |
                    qwert-${{github.ref_name}}-aarch64-linux-gnu.tar.gz
            
    release:
        name: Github Release
        needs: [build]
        runs-on: "ubuntu-latest"
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                name: release-binaries
            - name: Release
              uses: ncipollo/release-action@main
              with:
                allowUpdates: false
                artifactErrorsFailBuild: true
                bodyFile: "Changes.md"
                artifacts: "qwert-${{github.ref_name}}-aarch64-linux-gnu.tar.gz"